[global]
host=127.0.0.1
user=scms
password=NmMy123!
database= scms
sourcedir = /opt/tools/delschedule/data
desturl   = http://172.25.116.8:6080/axis/services/ctms
lspid     = NMSMP
cspid     = BATCH 
ftpurl    = ftp://wacos:wacos@172.25.130.5:21/
