POST http://127.0.0.1:5000/requestService
Content-Type: application/json

{
    "UserID": "13090003789",
    "AccountType": 1,
    "Carrier": 3,
    "Province": "江苏",
    "City": "南京",
    "TradeFlag": 2,
    "TeamID": 1,
    "UserType": 1,
    "State": 1,
    "ProductList": "productList001",
    "ActiveTime": "20211218171419",
    "UpdateTime": "20220428131313",
    "ExpireTime": "20290428131313"
}