# 导入所有模型，确保 SQLAlchemy 能发现它们
from app.models.user import User
from app.models.project import Project
from app.models.milestone import Milestone
from app.models.issue import Issue
from app.models.risk import Risk
from app.models.manday import ManDay
from app.models.sys_dict import SysDict
from app.models.weekly_progress import WeeklyProgress
